let recolectores = [
    {
        "CLAVE": 1,
        "PATERNO": "GALLARDO",
        "MATERNO": "VIGIL",
        "NOMBRE": "ING. MARCO",
        "DOMICILIO": "CALLE DEL BARRIO",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "XXXXX",
        "REG_IMSS": "",
        "PUESTO": 1,
        "DES_PUESTO": "DIRECTOR",
        "FECHA_ALTA": "20070728",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 2,
        "PATERNO": "BURGOS",
        "MATERNO": "LOPEZ",
        "NOMBRE": "ALMA PATRICIA",
        "DOMICILIO": "CONOCIDO",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 2,
        "DES_PUESTO": "ADMINISTRADOR",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 3,
        "PATERNO": "LOPEZ",
        "MATERNO": "NUÑEZ",
        "NOMBRE": "OCEAN, JESUS ANTONIO",
        "DOMICILIO": "CONOCIDO",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 12,
        "DES_PUESTO": "GERENTE DE OPERACIONES",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 4,
        "PATERNO": "FLORES",
        "MATERNO": "ZARATE",
        "NOMBRE": "JOSE ANGEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20121219",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 5,
        "PATERNO": "VELAZQUEZ",
        "MATERNO": "GUERRERO",
        "NOMBRE": "RODRIGO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 6,
        "PATERNO": "RUTA ACEITE 2",
        "MATERNO": "",
        "NOMBRE": "JUAN CARLOS SOTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 7,
        "PATERNO": "GRACIANO",
        "MATERNO": "URIAS",
        "NOMBRE": "MIGUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 8,
        "PATERNO": "CORTEZ",
        "MATERNO": "",
        "NOMBRE": "RAUL ADRIAN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 9,
        "PATERNO": "RUTA ACEITE",
        "MATERNO": "",
        "NOMBRE": "ANTONIO OROZCO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 10,
        "PATERNO": "OROZCO",
        "MATERNO": "",
        "NOMBRE": "ARMANDO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 11,
        "PATERNO": "OROZCO",
        "MATERNO": "",
        "NOMBRE": "ANTONIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20080507",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 12,
        "PATERNO": "RUTA OLAGUE",
        "MATERNO": "",
        "NOMBRE": "JESUS OLAGUE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20080507",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 0,
        "PATERNO": "NO DEFINIDO",
        "MATERNO": "",
        "NOMBRE": "",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 0,
        "DES_PUESTO": "",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 13,
        "PATERNO": "RODRIGUEZ",
        "MATERNO": "",
        "NOMBRE": "GABRIEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 14,
        "PATERNO": "BURGUENO",
        "MATERNO": "",
        "NOMBRE": "MARCO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20080619",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 15,
        "PATERNO": "RUIZ",
        "MATERNO": "RODRIGUEZ",
        "NOMBRE": "ALMA ELBA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 16,
        "PATERNO": "DE LA CRUZ DIAZ",
        "MATERNO": "",
        "NOMBRE": "MARIO ALBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 17,
        "PATERNO": "URRECHA",
        "MATERNO": "LOPEZ",
        "NOMBRE": "ALAN SAUL",
        "DOMICILIO": "",
        "ESTADO": 26,
        "CIUDAD": 30,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 18,
        "PATERNO": "RODRIGUEZ",
        "MATERNO": "OVALLE",
        "NOMBRE": "ALMA ELVA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 19,
        "PATERNO": "RUIZ",
        "MATERNO": "",
        "NOMBRE": "FIDENCIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "RURF820123FK2",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 20,
        "PATERNO": "CORRALES",
        "MATERNO": "",
        "NOMBRE": "ERNESTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 21,
        "PATERNO": "IMPORTACION",
        "MATERNO": "",
        "NOMBRE": "CHOFER PIPA GCI",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 22,
        "PATERNO": "MANCILLA",
        "MATERNO": "JARAMILLO",
        "NOMBRE": "RICARDO 2",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 23,
        "PATERNO": "ARI�AGA",
        "MATERNO": "",
        "NOMBRE": "ROBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 24,
        "PATERNO": "VAZQUEZ",
        "MATERNO": "",
        "NOMBRE": "CARLOS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 25,
        "PATERNO": "ENSENADA 2",
        "MATERNO": "",
        "NOMBRE": "VALENTE ARAIZA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 26,
        "PATERNO": "CARGA METAL",
        "MATERNO": "",
        "NOMBRE": "ECO RECYCLING",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 27,
        "PATERNO": "REC. BASURA",
        "MATERNO": "",
        "NOMBRE": "GRUPO GEN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 28,
        "PATERNO": "CASTRO",
        "MATERNO": "",
        "NOMBRE": "SAUL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 29,
        "PATERNO": "MARTINEZ",
        "MATERNO": "",
        "NOMBRE": "ESTEBAN SAUL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 30,
        "PATERNO": "CANCELADA",
        "MATERNO": "",
        "NOMBRE": "BOLETA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 31,
        "PATERNO": "MERCADO",
        "MATERNO": "JIMENEZ",
        "NOMBRE": "ISRAEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20120727",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 32,
        "PATERNO": "DE LA ROSA",
        "MATERNO": "",
        "NOMBRE": "AURELIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 33,
        "PATERNO": "GRACIANO",
        "MATERNO": "",
        "NOMBRE": "JUAN CARLOS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 1,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 34,
        "PATERNO": "GUTIERREZ (EDA)",
        "MATERNO": "",
        "NOMBRE": "JULIO CESAR",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 1,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 35,
        "PATERNO": "BEEF (EDA)",
        "MATERNO": "",
        "NOMBRE": "LA COSTILLA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 1,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 36,
        "PATERNO": "SA DE CV",
        "MATERNO": "",
        "NOMBRE": "RENPRO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 37,
        "PATERNO": "FLORES",
        "MATERNO": "",
        "NOMBRE": "JOSE CANDELARIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 38,
        "PATERNO": "BERNAL",
        "MATERNO": "",
        "NOMBRE": "MIGUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 39,
        "PATERNO": "AMEZCUA",
        "MATERNO": "BONILLA",
        "NOMBRE": "ELIAZAR",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 40,
        "PATERNO": "SPECIALISTS",
        "MATERNO": "",
        "NOMBRE": "SMC GREASE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 41,
        "PATERNO": "RUTA LA MISION",
        "MATERNO": "",
        "NOMBRE": "CHOFER ASIGNADO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 42,
        "PATERNO": "CHAVARRIA",
        "MATERNO": "VELAZQUEZ",
        "NOMBRE": "JOSUE",
        "DOMICILIO": "PLANTA",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 6,
        "DES_PUESTO": "AUXILIAR ADMINISTRATIVO",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 43,
        "PATERNO": "RODRIGUEZ",
        "MATERNO": "",
        "NOMBRE": "ING. FRANCISCO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 6,
        "DES_PUESTO": "AUXILIAR ADMINISTRATIVO",
        "FECHA_ALTA": "20100927",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 44,
        "PATERNO": "MONTERO",
        "MATERNO": "OCA�A",
        "NOMBRE": "MANUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 45,
        "PATERNO": "MARTINEZ",
        "MATERNO": "ROJAS",
        "NOMBRE": "DAVID",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20110806",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 46,
        "PATERNO": "LEAL",
        "MATERNO": "MENDEZ",
        "NOMBRE": "RENE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20110811",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 47,
        "PATERNO": "MONTIEL",
        "MATERNO": "LOPEZ",
        "NOMBRE": "RAUL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 1,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 48,
        "PATERNO": "LICEA",
        "MATERNO": "",
        "NOMBRE": "FRANCISCO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 14,
        "DES_PUESTO": "LOGISTICA Y ABASTECIMIENTOS",
        "FECHA_ALTA": "20190903",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 49,
        "PATERNO": ".",
        "MATERNO": "CRUZ",
        "NOMBRE": "MANUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 50,
        "PATERNO": "PONCE",
        "MATERNO": "PEREZ",
        "NOMBRE": "HUMBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20120707",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 2,
        "COM_SHR": 0
    },
    {
        "CLAVE": 51,
        "PATERNO": "HIGUERA",
        "MATERNO": "LOPEZ",
        "NOMBRE": "RAMON",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 52,
        "PATERNO": ".",
        "MATERNO": "",
        "NOMBRE": "SAMEX",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 53,
        "PATERNO": "BOLA�OS",
        "MATERNO": "MORALES",
        "NOMBRE": "ROYER DAVID",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20120713",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 54,
        "PATERNO": "BIO REGENERADORA",
        "MATERNO": "",
        "NOMBRE": "PIPA",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 55,
        "PATERNO": "ROSAS",
        "MATERNO": "ORTEGA",
        "NOMBRE": "ELMER",
        "DOMICILIO": "REAL DE SAN FERNANDO 437 COLONIA REAL DE SAN FERNANDO",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20120909",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 56,
        "PATERNO": "IMPORTACION",
        "MATERNO": "",
        "NOMBRE": "CHOFER PIPA JOSE NAVARRO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 57,
        "PATERNO": "FERRECIN",
        "MATERNO": "MEXICALI",
        "NOMBRE": "GUSTAVO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 58,
        "PATERNO": "REBOLLEDO",
        "MATERNO": "",
        "NOMBRE": "JUAN JOSE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 59,
        "PATERNO": "PORRAS",
        "MATERNO": "",
        "NOMBRE": "FELIX",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 60,
        "PATERNO": "HERNANDEZ",
        "MATERNO": "",
        "NOMBRE": "MIGUEL ANGEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 61,
        "PATERNO": "MARQUEZ",
        "MATERNO": "",
        "NOMBRE": "JOSE MANUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 62,
        "PATERNO": "PEREZ",
        "MATERNO": "",
        "NOMBRE": "ABEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 63,
        "PATERNO": "MERCADO",
        "MATERNO": "",
        "NOMBRE": "ROBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 64,
        "PATERNO": "TALLOW INC.",
        "MATERNO": "",
        "NOMBRE": "PIPA TUCSON",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 65,
        "PATERNO": "MARQUEZ",
        "MATERNO": "",
        "NOMBRE": "JOSE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 3,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130110",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 66,
        "PATERNO": "BUSTAMANTE",
        "MATERNO": "MONREAL",
        "NOMBRE": "ENRIQUE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130422",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 67,
        "PATERNO": "RAMIREZ",
        "MATERNO": "",
        "NOMBRE": "ALEJANDRO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130513",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 68,
        "PATERNO": "CISNERO",
        "MATERNO": "",
        "NOMBRE": "CESAR",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130601",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 69,
        "PATERNO": "BLANCO",// sosa
        "MATERNO": "",
        "NOMBRE": "CARLOS",// antonio
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130609",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 10
    },
    {
        "CLAVE": 70,
        "PATERNO": "GONZALEZ",
        "MATERNO": "SANCHEZ",
        "NOMBRE": "BENJAMIN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20130820",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 71,
        "PATERNO": "LA CANASTA",
        "MATERNO": "",
        "NOMBRE": "DISTRIBUIDORA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 72,
        "PATERNO": "TINOCO",
        "MATERNO": "",
        "NOMBRE": "NICOLAS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20131101",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 73,
        "PATERNO": "SOSA",
        "MATERNO": "",
        "NOMBRE": "AANTONIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20131211",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 74,
        "PATERNO": "VEGA",
        "MATERNO": "",
        "NOMBRE": "OMAR",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140603",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 75,
        "PATERNO": "MEZA",
        "MATERNO": "",
        "NOMBRE": "JORGE ARTURO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140501",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 76,
        "PATERNO": "ARENAS",
        "MATERNO": "",
        "NOMBRE": "BALDOMERO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140501",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 77,
        "PATERNO": "ZABALA",
        "MATERNO": "",
        "NOMBRE": "ISMAEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140617",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 78,
        "PATERNO": "HERRERA MENDOZA",
        "MATERNO": "",
        "NOMBRE": "JOSE HUGO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140717",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 79,
        "PATERNO": "MURUA",
        "MATERNO": "",
        "NOMBRE": "JESUS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140805",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 80,
        "PATERNO": "MORUA",
        "MATERNO": "",
        "NOMBRE": "ADRIAN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140804",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 81,
        "PATERNO": "JIMENEZ",
        "MATERNO": "",
        "NOMBRE": "JESUS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 82,
        "PATERNO": "LOPEZ",
        "MATERNO": "",
        "NOMBRE": "EDUARDO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20140501",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 83,
        "PATERNO": "TERRAZAS",
        "MATERNO": "",
        "NOMBRE": "JOSE LUIS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20141104",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 84,
        "PATERNO": "RAMIREZ",
        "MATERNO": "",
        "NOMBRE": "GABRIEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 3,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20141211",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 85,
        "PATERNO": "GOMEZ",
        "MATERNO": "",
        "NOMBRE": "MARTIN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20141211",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 86,
        "PATERNO": "ZAVALA",
        "MATERNO": "",
        "NOMBRE": "ABEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20150107",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 87,
        "PATERNO": "QUINTO",
        "MATERNO": "GRANDA",
        "NOMBRE": "GUILLERMO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20150217",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 88,
        "PATERNO": "ARENAS",
        "MATERNO": "",
        "NOMBRE": "JOSE ANGEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20150311",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 89,
        "PATERNO": "GODINEZ",
        "MATERNO": "",
        "NOMBRE": "JOEL",
        "DOMICILIO": "MEXICALI",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20150506",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 90,
        "PATERNO": "MAYORGA",
        "MATERNO": "",
        "NOMBRE": "SABINO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20150509",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 91,
        "PATERNO": "SANCHEZ",
        "MATERNO": "",
        "NOMBRE": "JAIR",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160316",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 92,
        "PATERNO": "BUSTAMANTE",
        "MATERNO": "",
        "NOMBRE": "ENRIQUE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160301",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 93,
        "PATERNO": ".",
        "MATERNO": ".",
        "NOMBRE": "SU KARNE",
        "DOMICILIO": ".",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 94,
        "PATERNO": ".",
        "MATERNO": ".",
        "NOMBRE": "LA CANASTA",
        "DOMICILIO": ".",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 95,
        "PATERNO": ".",
        "MATERNO": ".",
        "NOMBRE": "DISTRIBUIDORA SANCHEZ",
        "DOMICILIO": ".",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 96,
        "PATERNO": ".",
        "MATERNO": ".",
        "NOMBRE": "SOLES",
        "DOMICILIO": ".",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 97,
        "PATERNO": ".",
        "MATERNO": ".",
        "NOMBRE": "CARNICERIA MENDOZA",
        "DOMICILIO": ".",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 98,
        "PATERNO": ".",
        "MATERNO": "",
        "NOMBRE": "ARTURO MEZA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160512",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 99,
        "PATERNO": "EALIZ",
        "MATERNO": "",
        "NOMBRE": "EALYZ",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160518",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 100,
        "PATERNO": "ROMERO",
        "MATERNO": "",
        "NOMBRE": "JORGE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160527",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 101,
        "PATERNO": "BAJA",
        "MATERNO": "",
        "NOMBRE": "PROMEX",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160601",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 102,
        "PATERNO": "MONTES",
        "MATERNO": "",
        "NOMBRE": "RODRIGUEZ",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160601",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 103,
        "PATERNO": "MONTES",
        "MATERNO": "",
        "NOMBRE": "RODRIGO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160601",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 104,
        "PATERNO": "PROMEX",
        "MATERNO": "",
        "NOMBRE": "BAJA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160603",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 105,
        "PATERNO": "LEOBARDO",
        "MATERNO": "",
        "NOMBRE": "GUTIERREZ",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160603",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 106,
        "PATERNO": "URRECHA",
        "MATERNO": "",
        "NOMBRE": "ALAN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160706",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 107,
        "PATERNO": "ARI�AGA",
        "MATERNO": "ACEVEDO",
        "NOMBRE": "JOSE ROBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160708",
        "FECHA_BAJA": "20160708",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 108,
        "PATERNO": "ANZURES",
        "MATERNO": "",
        "NOMBRE": "JOSE",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160711",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 109,
        "PATERNO": "RODRIGUEZ",
        "MATERNO": "",
        "NOMBRE": "JOSE RODRIGUEZ",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160718",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 110,
        "PATERNO": "CORREA",
        "MATERNO": "MIRANDA",
        "NOMBRE": "CESAR EDUARDO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160817",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 111,
        "PATERNO": "CORONADO",
        "MATERNO": "MORALES",
        "NOMBRE": "JORGE HUGO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160818",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 112,
        "PATERNO": "DUE�AS",
        "MATERNO": "",
        "NOMBRE": "JOSE MANUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160827",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 113,
        "PATERNO": "GURROLA",
        "MATERNO": "(RASTRO)",
        "NOMBRE": "JUAN ANDRES",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160827",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 114,
        "PATERNO": "GURROLA",
        "MATERNO": "(RUTA)",
        "NOMBRE": "JUAN ANDRES",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160827",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 10,
        "COM_SHR": 20
    },
    {
        "CLAVE": 115,
        "PATERNO": "MACFARLAN",
        "MATERNO": "",
        "NOMBRE": "LUIS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160901",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 116,
        "PATERNO": "RUBIO",
        "MATERNO": "",
        "NOMBRE": "MARIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20160920",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 117,
        "PATERNO": "GUANAJUATO",
        "MATERNO": "",
        "NOMBRE": "LEON",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20161104",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 118,
        "PATERNO": "BLANCA",
        "MATERNO": "",
        "NOMBRE": "CUESTA",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20161114",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 119,
        "PATERNO": "MORENO",
        "MATERNO": "",
        "NOMBRE": "ALFONSO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20170208",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 120,
        "PATERNO": "CAZAREZ",
        "MATERNO": "",
        "NOMBRE": "JESUS",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20170225",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 121,
        "PATERNO": "DE LA CRUZ",
        "MATERNO": "",
        "NOMBRE": "MARIO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20170327",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 122,
        "PATERNO": "MANCILLAS",
        "MATERNO": "OROZCO",
        "NOMBRE": "JOSE ROMARIO",
        "DOMICILIO": "TIJUANA",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20170508",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 123,
        "PATERNO": "TORRES",
        "MATERNO": "BARBOZA",
        "NOMBRE": "DANIEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 124,
        "PATERNO": "OROZCO",
        "MATERNO": "LOMELI",
        "NOMBRE": "GUILLERMO",
        "DOMICILIO": "CALLE MULEGE NO. 8, COL. GUAYCURA",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "OOLG0001267Y8",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20170803",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 125,
        "PATERNO": "LICEA",
        "MATERNO": "",
        "NOMBRE": "FRANCISCO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 5,
        "DES_PUESTO": "VENDEDOR",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 126,
        "PATERNO": "REYES",
        "MATERNO": "LOPEZ",
        "NOMBRE": "IGNACIO",
        "DOMICILIO": "CALLE EMILIANO ZAPATA 12688",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20171104",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 127,
        "PATERNO": "ARI�AGA",
        "MATERNO": "ACEVEDO",
        "NOMBRE": "JOSE ROBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20180126",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 128,
        "PATERNO": "ARI�AGA",
        "MATERNO": "ACEVEDO",
        "NOMBRE": "JOSE ROBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 129,
        "PATERNO": "DIAZ MIORENO",
        "MATERNO": "",
        "NOMBRE": "MANUEL FERNANDO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20180811",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 130,
        "PATERNO": "VELAZQUEZ",
        "MATERNO": "",
        "NOMBRE": "RODRIGO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20181029",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 131,
        "PATERNO": "ROMARIO",
        "MATERNO": "MACILLAS",
        "NOMBRE": "JOSE",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20181120",
        "FECHA_BAJA": "20181120",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 132,
        "PATERNO": "PANDURO",
        "MATERNO": "MU�OZ",
        "NOMBRE": "RUBEN ALEJANDRO",
        "DOMICILIO": "AV. PASEO DEL REFUGIO M. 1 L.20",
        "ESTADO": 2,
        "CIUDAD": 3,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20181222",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 133,
        "PATERNO": "ALVARADO",
        "MATERNO": "",
        "NOMBRE": "MIGUEL",
        "DOMICILIO": "TIJUANA",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20181223",
        "FECHA_BAJA": "20181223",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 134,
        "PATERNO": "TALAMANTES",
        "MATERNO": "",
        "NOMBRE": "LUIS",
        "DOMICILIO": "MEXICALI",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190202",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 135,
        "PATERNO": "AVILA",
        "MATERNO": "CARRETERO",
        "NOMBRE": "JOSE ROSARIO",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190405",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 136,
        "PATERNO": "VAZQUEZ",
        "MATERNO": "",
        "NOMBRE": "MIGUEL ANGEL",
        "DOMICILIO": "AV.GUANAJUATO  # 70 LOMA ALTA",
        "ESTADO": 2,
        "CIUDAD": 3,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190601",
        "FECHA_BAJA": "20190601",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 137,
        "PATERNO": "RUIZ",
        "MATERNO": "LOPEZ",
        "NOMBRE": "JORGE MARTIN",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190704",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 138,
        "PATERNO": "NOVOA",
        "MATERNO": "",
        "NOMBRE": "FIDEL",
        "DOMICILIO": "MEXICALI",
        "ESTADO": 2,
        "CIUDAD": 2,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190808",
        "FECHA_BAJA": "20190808",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 139,
        "PATERNO": "DIAZ",
        "MATERNO": "",
        "NOMBRE": "MANUEL",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190817",
        "FECHA_BAJA": "20190817",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 140,
        "PATERNO": "DE LA CRUZ",
        "MATERNO": "DIAZ",
        "NOMBRE": "MARIO ALBERTO",
        "DOMICILIO": "",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 141,
        "PATERNO": "DUE�AS",
        "MATERNO": "CAMACHO",
        "NOMBRE": "MANUEL",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20190930",
        "FECHA_BAJA": "20190930",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 142,
        "PATERNO": "LANDA",
        "MATERNO": "MAGANA",
        "NOMBRE": "ISAAC",
        "DOMICILIO": "PROGRESO TIJUANA",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20200103",
        "FECHA_BAJA": "20200103",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 143,
        "PATERNO": "ARENAS",
        "MATERNO": "CORDOBA",
        "NOMBRE": "EUSEBIO",
        "DOMICILIO": "CALLE QUELITE #25003 EL FLORIDO SEGUNDA SECCION",
        "ESTADO": 2,
        "CIUDAD": 4,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "20200904",
        "FECHA_BAJA": "20200904",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 144,
        "PATERNO": "CORONADO",
        "MATERNO": "",
        "NOMBRE": "JORGE",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 145,
        "PATERNO": "FERNANDO",
        "MATERNO": "TORREZ",
        "NOMBRE": "RECOLECTORA BAJA",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 146,
        "PATERNO": "ALVARES",
        "MATERNO": "",
        "NOMBRE": "RECOLECTORA",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    },
    {
        "CLAVE": 147,
        "PATERNO": "MARTINEZ",
        "MATERNO": "",
        "NOMBRE": "JESUS ",
        "DOMICILIO": "",
        "ESTADO": 0,
        "CIUDAD": 0,
        "RFC": "",
        "REG_IMSS": "",
        "PUESTO": 7,
        "DES_PUESTO": "CHOFER",
        "FECHA_ALTA": "",
        "FECHA_BAJA": "",
        "HORARIO": "",
        "LICENCIA": "",
        "DEPTO": "",
        "COM_RECOL": 0,
        "COM_SHR": 0
    }

]

module.exports = recolectores