let rutas = [
    {
        "RUTA": "",
        "DESCRIP": "NO TIENE RUTA DEFINIDA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-1",
        "DESCRIP": "GUILLERMO OROZCO LOMELI",
        "DIA_LUN": 0,
        "DIA_MAR": 1,
        "DIA_MIE": 0,
        "DIA_JUE": 1,
        "DIA_VIE": 0,
        "DIA_SAB": 1,
        "NO": 1
    },
    {
        "RUTA": "RUTA-2",
        "DESCRIP": "ANTONIO SOSA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 2
    },
    {
        "RUTA": "RUTA-3",
        "DESCRIP": "ARMANDO OROZCO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 3
    },
    {
        "RUTA": "RUTA-4",
        "DESCRIP": "JUAN ANDRES GURROLA V",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 4
    },
    {
        "RUTA": "RUTA-5",
        "DESCRIP": "JESUS OLAGUE (RUTA OLAGUE)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 5
    },
    {
        "RUTA": "RUTA-6",
        "DESCRIP": "JUAN CARLOS SOTO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 6
    },
    {
        "RUTA": "RUTA-7",
        "DESCRIP": "ENRIQUE BUSTAMANTE.",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 7
    },
    {
        "RUTA": "RUTA-8",
        "DESCRIP": "FIDENCIO RUIZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 8
    },
    {
        "RUTA": "RUTA-9",
        "DESCRIP": "GABRIEL RODRIGUEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 9
    },
    {
        "RUTA": "RUTA 10",
        "DESCRIP": "ANTONIO OROZCO (RUTA ACEITE)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 10
    },
    {
        "RUTA": "RUTA-11",
        "DESCRIP": "TEODORO VELAZQUEZ ALMEIDA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 11
    },
    {
        "RUTA": "RUTA-12",
        "DESCRIP": "ALAN URRECHA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 12
    },
    {
        "RUTA": "RUTA-13",
        "DESCRIP": "ERNESTO CORRALES",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 13
    },
    {
        "RUTA": "RUTA-14",
        "DESCRIP": "OCEAN. JOSE CRUZ JIMENEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 14
    },
    {
        "RUTA": "RUTA-15",
        "DESCRIP": "ERNESTO CORRALES",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 15
    },
    {
        "RUTA": "RUTA-16",
        "DESCRIP": "MARIO DE LA CRUZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 16
    },
    {
        "RUTA": "RUTA-17",
        "DESCRIP": "VALENTE ARAIZA ENSENADA 2",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 17
    },
    {
        "RUTA": "RUTA-18",
        "DESCRIP": "ECO RECYCLING (METAL)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 18
    },
    {
        "RUTA": "RUTA-19",
        "DESCRIP": "GRUPO GEN (RECOLECCION BASURA)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 19
    },
    {
        "RUTA": "RUTA-20",
        "DESCRIP": "PARTICULAR (SAUL CASTRO)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 20
    },
    {
        "RUTA": "RUTA-21",
        "DESCRIP": "ESTEBAN SAUL MARTINEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 21
    },
    {
        "RUTA": "RUTA-22",
        "DESCRIP": "CARLOS VAZQUEZ PE�A",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 22
    },
    {
        "RUTA": "RUTA-23",
        "DESCRIP": "CANCELADO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 23
    },
    {
        "RUTA": "RUTA-24",
        "DESCRIP": "NICOLAS TINOCO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 24
    },
    {
        "RUTA": "RUTA-25",
        "DESCRIP": "AURELIO DE LA ROSA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 25
    },
    {
        "RUTA": "RUTA-26",
        "DESCRIP": "MARCO BURGUE�O - CULIACAN",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 26
    },
    {
        "RUTA": "RUTA-27",
        "DESCRIP": "RENPRO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 27
    },
    {
        "RUTA": "RUTA-28",
        "DESCRIP": "DAVID MARTINEZ ROJAS",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-29",
        "DESCRIP": "SR. RENE LEAL MENDEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-30",
        "DESCRIP": "ELIAZAR AMEZCUA BONILLA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-31",
        "DESCRIP": "MANUEL CRUZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-32",
        "DESCRIP": "SABINO MAYORGA",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-33",
        "DESCRIP": "ISRAEL MERCADO JIMENEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA 34",
        "DESCRIP": "ENRIQUE BUSTAMANTE",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R001",
        "DESCRIP": "CARLOS BLANCO", //JOSE ROMARIO MANCILLAS OROZCO
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R002",
        "DESCRIP": "JESUS MARQUEZ", //ANTONIO SOSA
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA -35",
        "DESCRIP": "JOSE ANZURES",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA -36",
        "DESCRIP": "JOSE ANGEL ARENAS",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA -37",
        "DESCRIP": "JAIR SANCHEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R003",
        "DESCRIP": "ABEL ZAVALA GONZALEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R004",
        "DESCRIP": "NICOLAS TINOCO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R005",
        "DESCRIP": "RODRIGO VELAZQUEZ",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "130",
        "DESCRIP": "RODRIGO VELAZQUEZ (FLORIDOS)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA -38",
        "DESCRIP": "RODRIGO VELAZQUEZ (PROPIO)",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "R-39",
        "DESCRIP": "RANCHO DEL TIO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "40",
        "DESCRIP": "EUSEBIO ARENAS",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    },
    {
        "RUTA": "RUTA-41",
        "DESCRIP": "JORGE CORONADO",
        "DIA_LUN": 0,
        "DIA_MAR": 0,
        "DIA_MIE": 0,
        "DIA_JUE": 0,
        "DIA_VIE": 0,
        "DIA_SAB": 0,
        "NO": 0
    }
]
module.exports =  rutas 