const Cliente = require("./Cliente")
const Destino = require("./Destino")
const Receptor = require("./Receptor")
const Recolector = require("./Recolector")
const Ruta = require("./Ruta")
const Transporte = require("./Transporte")
const Unidad = require("./Unidad")
const Vehiculo = require("./Vehiculo")

class Manifiesto {
    "ANIO"= 2022 
		"ARTICULOS"= [] 
		"AUTORIZA"= "" 
		"BANCO"= "" 
		"CAL_CHOFER"= "" 
		"CAL_FECHA"= "" 
		"CAL_IVA"= 0 
		"CAL_SEMANA"= 0 
		"CAL_STATUS"= 0 
		"CHEQUE"= "" 
		"CHOFER"= 0
		"CLAVE"= "AA" 
		"CLIENTE"= 0
		"CLIENTE_"= Cliente
		"CUENTA"= "" 
		"DEPTO"= 0 
		"DESTI"= 0 
		"DESTINO"= Destino
		"DOCUMENTO"= "" 
		"ENTREGA"= "" 
		"FACTURA"= "" 
		"FACTURAS"= "" 
		"FECHA"= "" 
		"FECHA_ENT"= "" 
		"FECHA_IMP"= "" 
		"FECHA_PAGO"= "" 
		"FEC_DESTI"= "" 
		"FEC_TRANS"= "" 
		"FOLIO"= "" 
		"FORMA_PAG"= "" 
		"ID_NUMERACION"= "" 
		"ID_SERIE"= "AA" 
		"IMPORTACIO"= 0 
		"IMPORTE"= 0 
		"IMPORTE_D"= 0 
		"IMPORTE_P"= 0 
		"IMP_PAGO"= 0 
		"IVA"= 0 
		"LAB"= "" 
		"MONEDA"= 1 
		"MONE_PAGO"= 0 
		"NACIONAL"= 0 
		"OBSER"= "" 
		"PAGADA"= "" 
		"PEDIMENTO"= "" 
		"PLANTA"= 1 
		"PROVEEDOR"=  
		"RECEPTOR"= Receptor
		"RECIBE"= 0 
		"RECOLECTOR"= Recolector
		"REQUISICIO"= "" 
		"RETENCION"= 0 
		"RET_IVA"= 0 
		"RUTA"= "RUTA-4" 
		"RUTA_"= Ruta
		"SEC_PAGO"= 0 
		"SEMANA"= 0
		"SOLICITO"= "" 
		"STATUS"= 0 
		"SUB_TOTAL"= 0 
		"TIPO_ABONO"= "" 
		"TIPO_PAGO"= "" 
		"TOTAL"= 0 
		"TOTAL_KG"= 0 
		"TRANS"= 0 
		"TRANSPORTE"= Transporte
		"T_CAMBIO"= 0 
		"UNIDAD"= 1 
		"UNIDAD_"= Unidad
		"VEHICULO"= Vehiculo
}